# Generated by Django 2.1.1 on 2018-10-11 22:21

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PLACE', 'Place or populated area'), ('STATE', 'State of the United States'), ('PARK', 'US National Park')], default='PLACE', max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('area', models.BigIntegerField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='GeoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_center_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.GeoUser')),
            ],
        ),
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='unknown', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('time_last_played', models.DateTimeField(blank=True, null=True, verbose_name='time last played')),
                ('time_last_skipped', models.DateTimeField(blank=True, null=True, verbose_name='time last skipped')),
                ('tune_content', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTuneLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.GeoLocation')),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.Tune')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunes.GeoUser')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='tunes',
            field=models.ManyToManyField(to='tunes.Tune'),
        ),
        migrations.AlterUniqueTogether(
            name='geolocation',
            unique_together={('type', 'state', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tune',
            unique_together={('owner', 'author', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('owner', 'name')},
        ),
    ]
