# Generated by Django 2.1.1 on 2018-11-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0005_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='type',
            field=models.CharField(choices=[('COUNTY', 'Counties of the United States'), ('PLACE', 'Place or populated area'), ('STATE', 'State of the United States'), ('PARK', 'US National Park'), ('USER', 'User defined area')], default='USER', max_length=12),
        ),
        # migrations.AlterUniqueTogether(
        #     name='geolocation',
        #     unique_together=set(),
        # ),
    ]
