# Generated by Django 2.1.1 on 2018-11-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0006_auto_20181107_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(default='00', max_length=2),
        ),
        # migrations.AlterUniqueTogether(
        #     name='geolocation',
        #     unique_together=set(),
        # ),
    ]
